### ISSUE TITLE
Here's some finding when I test the service list provided by the project

### ISSUE THREAD

**Issue by dennyamarojr** [amitxv/PC-Tuning#111]
Appinfo which is Application Information is required by all the programs, if the service is disabled services.msc, cmd.exe and other programs could not be opened. To fix this the user need to restart to safe mode and re-enable the service.
Shell Hardware Detection - Not sure about this one, but I restore this service to default state and I was able to see my external drive and also unlock with the recovery from BitLocker encryption. When disabled, show the message Could not access the drive or Location is not accessible.
DevicesFlowUserSvc [DevicesFlow] (required by system tray and Bluetooth & Devices)
DevicesFlowUserSvc_9c935 [DevicesFlow_9c935] (required by system tray and Bluetooth & Devices)
CaptureService [CaptureService] (Required by Snipping Tool)
CaptureService_9c935 (Required by Snipping Tool)
DsSvc [Data Sharing Service] (Required by Snipping Tool, if disabled shows 'Failed to open file' in Snipping tool.)

**Comment by amitxv** [comment]
Can you provide more context? What Windows version are you using?

Disabling Appinfo on every OS I have configured so far has not caused any problems. This could be due to UAC still being enabled while the luafv driver is disabled. You can try set the enablelua registry key to 0 and re-test disabling Appinfo.

I'm able to access my external USB drive with Shell Hardware Detection disabled on Windows 10 1803.

In the context of the guide, minimal services are supposed to be used to optimize for real-time tasks. By using Bluetooth whatsoever adds a latency penalty to the system and the Bluetooth device itself so I do not intend on whitelisting DevicesFlowUserSvc in the configuration file. What exactly do you mean by it breaks the tray? A picture could help.

Is CaptureService required for the legacy or snip and sketch? Please provide the Windows version you are using. Same for DsSvc. I'm able to use the legacy snipping tool on all versions of Windows I have configured, but I have not been able to test on Windows 11 because snipping tool is an appx package and gets removed in the (Remove Provisioned Appx Bloatware (Windows 8+))[https://github.com/amitxv/PC-Tuning/blob/main/docs/building.md#remove-provisioned-appx-bloatware-windows-8] step.

**Comment by dennyamarojr** [comment]
CaptureService is needed for Snip & Sketch, I'm using Windows 11 22H2.

The problem for DevicesFlowUserSvc is this one 
![image](https://user-images.githubusercontent.com/36896116/232356378-ae57dbc3-ace2-44ea-9aa4-0aa00e0cdbfc.png)

When you click the volume icon and want to change the volume manually has not effect, if the DevicesFlowUserSvc is disabled.
And when you go to Settings> Bluetooth & Devices. You can see the settings, when you click the window immediately close.

The UAC I will check here, and make the process you provided.

**Comment by amitxv** [comment]
I will keep in mind that CaptureService is required for Snip & Sketch but I have no plans to enable it by default in the .ini in the near future because it is an appx package and gets removed in the [Remove Provisioned Appx Bloatware (Windows 8+)](https://github.com/amitxv/PC-Tuning/blob/main/docs/building.md#remove-provisioned-appx-bloatware-windows-8) step. There are probably more services required for UWP in general.

Can you not change the volume with the volume slider/buttons on your keyboard or the legacy control panel?

I have no plans at all to enable anything Bluetooth related by default as I mentioned before:

> In the context of the guide, minimal services are supposed to be used to optimize for real-time tasks. By using Bluetooth whatsoever adds a latency penalty to the system and the Bluetooth device itself so I do not intend on whitelisting DevicesFlowUserSvc in the configuration file.

There are other services that are required for the control panel to open at all so I would have to restructure/enable a lot of drivers/services by default. At that point, you may as well just not disable services at all.
