### ISSUE TITLE
Start menu Windows 11 disabled after Services-Disable.bat

### ISSUE THREAD

**Issue by leondrelul** [amitxv/PC-Tuning#140]
Running the `Services-Disable.bat` also disables start menu. I know that the documentation says that installing Open-Shell is a "must", but i kinda want the standard look of windows. I'd like to know that what should I change in the `minimal-services.ini` to not disable the Windows 11 Start Menu and Windows 11 Search.

**Comment by amitxv** [comment]
I assume you haven't followed the [Handle Bloatware with Linux](https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#handle-bloatware-with-linux) step if the start menu is functioning with ``Services-Enable.bat`` because that step strips it. In that case, you can use [docs/debug-services.md](https://github.com/amitxv/PC-Tuning/blob/main/docs/debug-services.md) to determine what is required for the start menu to function. Read that document carefully as many people end up bricking their OS specifically on the filters step as they do not read it in full. Perhaps let me know what is required once you find out so that I can add it to ``minimal-services.ini`` by default but I would keep the Open-Shell recommendation in the guide.

I am working on removing the [Handle Bloatware with Linux](https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#handle-bloatware-with-linux) step completely to accommodate for things like this but luckily you have skipped it so you are fine.

**Comment by leondrelul** [comment]
I have come to a dead end. I've managed to get the start menu back by removing these lines from the `minimal-services.ini`:
```
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
C:\Windows\System32\RuntimeBroker.exe
C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
```

I still have a problem. On default if I open the start menu and i start typing, it automatically switches to the search, but I don't see this behaviour even if I remove all the lines from `[rename-binaries]`. I have started looking for what service could brick this behaviour, but so far I found nothing connected to it (on Windows 11).

**Comment by amitxv** [comment]
You need to follow [docs/debug-services.md](https://github.com/amitxv/PC-Tuning/blob/main/docs/debug-services.md) again with the new ``Services-Disable.bat`` script (in which, the ``REN`` commands are removed as you have identified that is what prevents the start menu from opening).

**Comment by amitxv** [comment]
After following [docs/debug-services.md](https://github.com/amitxv/PC-Tuning/blob/main/docs/debug-services.md), I was able to find out that ``UdkUserSvc`` is required. See if changing the start value for it in ``Services-Disable.bat`` from 4 to it's default value fixes the issue and let me know so that I can update ``minimal-services.ini``.
